version: '3.9'

services:

  party-panda-dev:
    user: 185:33
    image: 'docker.benevolo.de/stiehl-seine-perlen/party-panda:dev'
    restart: unless-stopped
    environment:
      QUARKUS_DATASOURCE_DB_KIND: POSTGRESQL
      QUARKUS_DATASOURCE_USERNAME: party-panda
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-dev:5432/event
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create
      QUARKUS_HTTP_CORS_ORIGINS: "https://dev.benevolo.de" ## allow frontend as origin

    networks:
      - party-panda
      - kafka

  postgres-dev:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: event
      POSTGRES_USER: party-panda
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /microservices/party-panda/postgres/data/:/var/lib/postgresql/data/
    networks:
      - party-panda

networks:
  kafka:
    external: true
  party-panda:
    external: true
