name: Build, test and deploy new docker image

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3
        with:
          ref: master

      - name: "Login to self hosted docker image registry"
        uses: docker/login-action@v2
        with:
          registry: docker.benevolo.de
          username: docker_admin
          password: ${{secrets.DOCKER_REGISTRY_ACCESS_PASSWORD}}

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17.0
          distribution: oracle
          cache: "maven"

      - name: "Build the maven package"
        run: ACCESS_TOKEN=${{secrets.GH_REGISTRY_ACCESS_PASSWORD}} DOCKER_REGISTRY_PASSWORD=${{secrets.DOCKER_REGISTRY_ACCESS_PASSWORD}} FORMREC_AZUREKEY=${{secrets.FORMREC_AZUREKEY}} mvn -X -s $GITHUB_WORKSPACE/.github/maven/settings.xml -B package --file pom.xml

      - name: "Build and test party-panda image"
        run: |
          docker build -f src/main/docker/Dockerfile.jvm \
          --tag docker.benevolo.de/stiehl-seine-perlen/party-panda:dev .

      - name: "Push frontend image to self hosted docker image registry"
        run: |
          docker push docker.benevolo.de/stiehl-seine-perlen/party-panda:dev

      - name: "Deploy new image"
        run: |
         curl -X POST https://portainer.benevolo.de/api/webhooks/bad99f1a-566c-4fe7-bcd6-8e967f5bd519